name: Accessible Autocomplete
author: mashalla
category: Widgets
tags: [Widget, UI, autocompletion, autocomplete, WAI ARIA]
# docs: https://github.com/juanparati/GooCompleter 
demo: http://mashalla.github.com/autoComplete
current: 1.0
